### ISSUE TITLE
Clean up the code 

### ISSUE THREAD

**Issue by Legedith** [Legedith/Danke_Schoen#1]

**Comment by vaderjunior** [comment]
Hey,
I would like to do this.
Anything i need to know prior?

**Comment by Legedith** [comment]
Just make sure all the sounds end up in a separate sounds folder. For the code, make functions where ever similar code is being used and add some exception handling.

**Comment by vaderjunior** [comment]
sure.

**Comment by vaderjunior** [comment]
Hey,
I have put the sounds in a different folder and put up a new function for handling the mp3 files. Will that be enough?

**Comment by Legedith** [comment]
Sure! Open a PR so I can have a look

**Comment by vaderjunior** [comment]
Hey,
Sorry for the delay. Ive opened a PR. Thanks

**Comment by cnguyen-uk** [comment]
I think the code can be cleaned up further - I've submitted a pull request to do this: https://github.com/Legedith/Danke_Schoen/pull/8

**Comment by cnguyen-uk** [comment]
I've also cleaned up and optimised the rest of the code with the following pull requests: https://github.com/Legedith/Danke_Schoen/pull/9, https://github.com/Legedith/Danke_Schoen/pull/10, https://github.com/Legedith/Danke_Schoen/pull/11

The README.md could use some grammar/punctuation/spelling checks too. Let me know if you want this to be done by opening an issue for it.
