### ISSUE TITLE
Add "hacktoberfest" topic

### ISSUE THREAD

**Issue by Johncs2d** [Legedith/Danke_Schoen#4]
Can u add the "hacktoberfest " topic this repository?

**Comment by Legedith** [comment]
I know how to add labels to issues. I don't know how I can add topics to repositories. If those two are different things, let me know how I can add topics to repos. 
P.s. I added the Hacktoberfest label to your PR while merging

**Comment by Johncs2d** [comment]
![image](https://user-images.githubusercontent.com/34950240/94995618-fe702c00-05d1-11eb-970b-80fdc50ccaf7.png)
U can add topic by editing repository details.

**Comment by Legedith** [comment]
Thanks!
